# Usa una imagen oficial de Python
FROM python:3.10-slim

# Establece el directorio de trabajo
WORKDIR /var/www

# Copia los requirements y los instala
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# Copia el resto del código
COPY . .

# Variables de entorno
ENV FLASK_APP=run.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5000
ENV FLASK_ENV=production

# Expone el puerto 5000
EXPOSE 5000

# Comando para ejecutar Flask
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000", "--app", "run.py"]

